import type { Theme } from '@/types/game';

export const THEMES: Record<string, Theme> = {
  default: {
    id: 'default',
    name: 'Minimal White',
    price: 0,
    description: 'Tema minimalis yang bersih dan simpel.',
    colors: {
      bg: '#0A0A1A',
      surface: '#12122A',
      primary: '#7C3AED',
      secondary: '#06B6D4',
      success: '#10B981',
      warning: '#F59E0B',
      danger: '#EF4444',
      textPrimary: '#F8FAFC',
      textSecondary: '#94A3B8',
      blocks: ['#7C3AED', '#06B6D4', '#10B981', '#F59E0B', '#EF4444', '#EC4899', '#8B5CF6'],
    },
  },
  dark_galaxy: {
    id: 'dark_galaxy',
    name: 'Dark Galaxy',
    price: 150,
    description: 'Board gelap dengan nuansa galaksi yang misterius.',
    colors: {
      bg: '#050510',
      surface: '#0A0A20',
      primary: '#9B59B6',
      secondary: '#3498DB',
      success: '#2ECC71',
      warning: '#F39C12',
      danger: '#E74C3C',
      textPrimary: '#ECF0F1',
      textSecondary: '#BDC3C7',
      blocks: ['#9B59B6', '#3498DB', '#2ECC71', '#F39C12', '#E74C3C', '#E91E63', '#673AB7'],
    },
    particleEffect: 'sparkle',
  },
  neon_city: {
    id: 'neon_city',
    name: 'Neon City',
    price: 200,
    description: 'Tema cyberpunk dengan efek neon yang futuristik.',
    colors: {
      bg: '#0D0D0D',
      surface: '#1A1A2E',
      primary: '#FF00FF',
      secondary: '#00FFFF',
      success: '#39FF14',
      warning: '#FFFF00',
      danger: '#FF3131',
      textPrimary: '#FFFFFF',
      textSecondary: '#A0A0A0',
      blocks: ['#FF00FF', '#00FFFF', '#39FF14', '#FFFF00', '#FF3131', '#FF1493', '#BF00FF'],
    },
    particleEffect: 'neon_trail',
  },
  ocean_deep: {
    id: 'ocean_deep',
    name: 'Ocean Deep',
    price: 150,
    description: 'Nuansa biru laut dalam yang menenangkan.',
    colors: {
      bg: '#001B3D',
      surface: '#002B5C',
      primary: '#0077B6',
      secondary: '#00B4D8',
      success: '#48CAE4',
      warning: '#FFD60A',
      danger: '#FF6B6B',
      textPrimary: '#CAF0F8',
      textSecondary: '#90E0EF',
      blocks: ['#0077B6', '#00B4D8', '#48CAE4', '#FFD60A', '#FF6B6B', '#ADE8F4', '#0096C7'],
    },
    particleEffect: 'bubble',
  },
  lava_world: {
    id: 'lava_world',
    name: 'Lava World',
    price: 200,
    description: 'Tema vulkanik dengan api dan magma.',
    colors: {
      bg: '#1A0500',
      surface: '#2D0A00',
      primary: '#FF4500',
      secondary: '#FF6347',
      success: '#FFA500',
      warning: '#FFD700',
      danger: '#FF0000',
      textPrimary: '#FFF5E6',
      textSecondary: '#FFDAB9',
      blocks: ['#FF4500', '#FF6347', '#FFA500', '#FFD700', '#FF0000', '#FF8C00', '#DC143C'],
    },
    particleEffect: 'fire',
  },
  nature_zen: {
    id: 'nature_zen',
    name: 'Nature Zen',
    price: 100,
    description: 'Tema alam yang hijau dan menenangkan.',
    colors: {
      bg: '#0D2818',
      surface: '#1A3C28',
      primary: '#4CAF50',
      secondary: '#8BC34A',
      success: '#66BB6A',
      warning: '#FFC107',
      danger: '#EF5350',
      textPrimary: '#E8F5E9',
      textSecondary: '#C8E6C9',
      blocks: ['#4CAF50', '#8BC34A', '#66BB6A', '#FFC107', '#EF5350', '#A5D6A7', '#388E3C'],
    },
    particleEffect: 'leaf',
  },
  rainbow_pop: {
    id: 'rainbow_pop',
    name: 'Rainbow Pop',
    price: 250,
    description: 'Warna-warni cerah untuk suasana ceria!',
    colors: {
      bg: '#1A0033',
      surface: '#2D0052',
      primary: '#FF1744',
      secondary: '#00E5FF',
      success: '#76FF03',
      warning: '#FFEA00',
      danger: '#FF3D00',
      textPrimary: '#FFFFFF',
      textSecondary: '#E0E0E0',
      blocks: ['#FF1744', '#00E5FF', '#76FF03', '#FFEA00', '#FF3D00', '#E040FB', '#FF9100'],
    },
    particleEffect: 'rainbow',
  },
  midnight_pro: {
    id: 'midnight_pro',
    name: 'Midnight Pro',
    price: 300,
    description: 'Premium gelap dengan aksen emas, terlihat mewah.',
    colors: {
      bg: '#0A0A0A',
      surface: '#141414',
      primary: '#D4AF37',
      secondary: '#FFD700',
      success: '#ADFF2F',
      warning: '#FFA500',
      danger: '#DC143C',
      textPrimary: '#F5F5DC',
      textSecondary: '#D3D3D3',
      blocks: ['#D4AF37', '#FFD700', '#ADFF2F', '#FFA500', '#DC143C', '#FF69B4', '#BA55D3'],
    },
    particleEffect: 'gold_sparkle',
  },
};

export const DEFAULT_THEME = 'default';

export function getTheme(themeId: string): Theme {
  return THEMES[themeId] || THEMES[DEFAULT_THEME];
}
